# NumPy for AI/ML – Conceptual & Technical Assessment

### Calibo AI Academy
### Module 3 – NumPy for AI/ML

**Submitted by:** Nuthakki Venkata Uma Sai Subrahmanyam.  
**Branch:** Information Technology  
**Batch:** 2nd batch

## Section A – Conceptual Understanding

#### A1.Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons.

Numpy arrays are designed for the numerical calculations.They usually use less memory and give the output quickly. It is used for the homogeneous numeric data.Numpy provides the inbuilt functions like mathematical functions, matrix operations,and tools commonly used in machine learning.

 Efficient numerical operations using vectorization.

 Build-in support for multidimensional arrays and mathematical calculations

#### A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

 Vectorization means performing an operation on an entire array instead of processing each element with an explicit python loop. Numpy implements many operations efficiently using compiled numerical routines. This can reduce python-level loop overhead when working with large datasets.

#### A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each?

 A* B--> It performs the element-wise multiplication and it uses the * symbol.

 A @ B --> It performs the Matrix Multiplication and it uses the @ symbol.

#### A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

 Broadcasting allows numpy to perfim element-wise operations on array with compacibile shapes without manually replicating smaller arrays.

#### A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

 Flatten and ravel is used to convert the multidimensional arrays into the 1D array.

 Flatten usually requires extra memory

 ravel usually requires less memory compared to the flatten.`ravel()` when a view is sufficient because it can avoid creating an unnecessary copy.

#### A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

For a 2D array, `axis=0` means the operation is performed down the rows, producing one result for each column. Axis=1 means the operation is performed across the columns, producing one result for each row.

#### A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Scaling numerical features is important because features with very different ranges can affect the training of many ML models.

- Normalization commonly scales values to a fixed range such as [0, 1]. Standardization transforms values so that the feature has approximately mean 0 and standard deviation 1. 

- Scaling can improve numerical stability and help optimization algorithms work more effectively.

#### A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?

Functions such as `np.nanmean()` are useful when a dataset contains NaN values and we want to calculate the mean while ignoring those missing values. `np.mean()` does not automatically ignore `NaN` values, so if the input contains a NaN, the resulting mean will normally also be `NaN`. `np.nanmean()` calculates the mean using the available non-NaN values.

#### A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

In the common ML convention, `X.shape = (samples, features)`. For images, the dimensions also include the image height, width, and color channels. A single RGB image of size 128 × 128 has shape (128, 128, 3). Therefore, a batch of 64 RGB images has the shape (64, 128, 128, 3).

#### A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

- Reproducibility is important because experiments should produce the same results when the same conditions are used. Random operations can produce different results on different runs. 

- Using `np.random.default_rng()` with a fixed seed makes the generated random numbers reproducible. For example, `np.random.default_rng(42)` creates a random number generator whose sequence can be reproduced using the same seed.



# Section-B: Predict the output:

### B1. Predict the exact output and/or resulting shape. Justify in one sentence.

### predicted output:
(3,3)

### Explanation:

It will performs the add operations with the array a and array b.

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)
#Explanation:
#It will performs the add operations with the array a and array b.

(3, 3)


## B2.Array slicing and reshaping:

## predicted output:[2,5]


# Explanation:
### The reshape function is used to reshpae the (1,7 )array into the 2 rows and 3 columns matrix.and it will print the 1 index value of the all rows.

In [ ]:
import numpy as np
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


# B3.Boolean filtering:

## predicted output: [10,20]

### Explanation:

It will prints the values divisible by 10 .


In [8]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

[10 20]


## B4.Transpose the matrix and Matrix Multiplication:

## Predicted Output:[[10,14] [14,20]]

### Explanation:

It will first transprose the matrix m and multiply with the m matrix and returns the output.
Transpose means it will converts the rows into columns and columns into rows.

In [ ]:
import numpy as np
m = np.array([[1, 2], [3, 4]])
print(m.T @ m)

[[10 14]
 [14 20]]


# B5. Mean with NaN:

## predicted output:nan 2.3333333

### Explanation:
np.mean(): It is used to calculate all the values in the array and take all the values.

np.nanmean():It is used to eliminate the nan values and calculate the mean to the remaining values in the array.

In [ ]:
import numpy as np
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


# B6. Conditional classification:

## Predicted output:[0,1,1]

### Explanation:

It will displays the values greater thean 15 are assigned 1; other values are assigned 0.

In [ ]:
import numpy as np
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


# B7. Array dimensions and size:

## predicted output: 2 12 

### Explanation:

ndim is used to return the array has two dimensions

size is used to find the no of elements in the array:like 3x4=12.

In [ ]:
import numpy as np
a = np.zeros((3, 4))
print(a.ndim, a.size)

2 12


# B8. Reverse rows and columns:

## Predicted output:[[12 11 10 9] [8 7 6 5] [4 3 2 1]]

### Explanation:
It will arange the array into the 3 rows and 4 columns.

: :-1 , : :-1 is used to reverse the rows and columns.

In [ ]:
import numpy as np
arr = np.arange(1, 13).reshape(3, 4)
print(arr[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# Section C – Coding / Implementation:

#### C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score >= 40) or 'F' (score < 40). 

#### Explanation:

np.where() is used to check the conditions if the condition is "True" the it returns the "Pass",if the condition is "False" then it returns the "Fail".

In [ ]:
import numpy as np
scores = np.array([35, 45, 60, 25, 80, 39, 40])
labels = np.where(scores >= 40, "P", "F")
print(labels)

['F' 'P' 'P' 'F' 'P' 'F' 'P']


# C2. Z-score standardization:

#### C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy .


#### Explanation:

The mean is subtracted from each value, and the result is divided by the standard deviation. This example uses the population standard deviation (ddof=0), which is NumPy's default.

In [ ]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std
x = np.array([10, 20, 30, 40, 50])
result = standardize(x)
print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


# C3. Combine two batches:

#### C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape combining the two batches is performed using the stacking process:

#### Explanation:
Stacking is used to comibne the two array using the function np.vstack();

Combined.shape() is used to print the shape of the combined matrix;

In [ ]:
import numpy as np
batch1 = np.array([[1, 2, 3],[4, 5, 6]])
batch2 = np.array([[7, 8, 9],[10, 11, 12]])
combined = np.vstack((batch1, batch2))
print(combined)
print("Shape:", combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)


# C4. Standardize a feature matrix:

#### C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression. 

#### Explanation:
The mean is subtracted from each value, and the result is divided by the standard deviation. This example uses the population standard deviation (ddof=0), which is NumPy's default.
s

In [13]:
X = np.random.default_rng(42).random((100, 5))
mean = X.mean(axis=0)
std = X.std(axis=0)
X_standardized = (X - mean) / std
print(X_standardized.shape)

(100, 5)


# C5. Linear model prediction and MSE:

#### Explanation:

Linear model prediction used to predict the output befre executing the program.
 Mse is also known as Mean Squared Error it is used to calculate the mean squared error of the model in machine learning

In [11]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_true = np.array([4.5, 6.0, 7.5])
y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)
print("Predictions:", y_pred)
print("MSE:", mse)

Predictions: [4.5 6.  7.5]
MSE: 0.0


# C6. Random data generation with a fixed seed:

#### C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed

#### Explanation:

normal() generates values from a standard normal distribution, and using the same seed produces the same sequence.

In [12]:
rng1 = np.random.default_rng(42)
rng2 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))
data2 = rng2.normal(size=(10, 3))
print("Shape:", data1.shape)
print("Identical:", np.array_equal(data1, data2))


Shape: (10, 3)
Identical: True


# C7. Normalize grayscale image pixels:

#### C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization

#### Explanation:

Dividing by 255 maps the usual grayscale pixel range to [0, 1].

In [ ]:
image = np.array([[0, 128],
                  [200, 255]], dtype=float)
normalized = image / 255.0
print(normalized)

# C8. Average pixel value of each image:

#### C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

#### Explanation:

axis=(1, 2, 3) averages height, width, and RGB channels for each image. The batch dimension (axis 0) is retained, producing four average values.


In [ ]:
rng = np.random.default_rng(42)
images = rng.integers(
    0, 256, size=(4, 28, 28, 3)
)
average_pixels = images.mean(axis=(1, 2, 3))
print("Batch shape:", images.shape)
print("Average values shape:", average_pixels.shape)
print("Average values:", average_pixels)

# Section D – Applied / Scenario-Based Problems:  

#### D1.You are given a raw 1D or 2D NumPy array containing NaN values.
#### (a) detect missing values,
#### (b) handle them appropriately and justify your strategy, and
#### (c) normalize or standardize the clean data before it is fed to a model.
#### Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

#### Explanation:

np.isnan() returns the boolean varray showing which elements contian NaN.
If the data contains the missing values then the prediction should be improper so here we just replace the missing values with mean values of the data, so the output is accurate and proper.
After replacing the missing value, the dat is standardized using its mean and standard deviation.

In [ ]:
# Step -1:CREATE A SAMPLE DATA:Create a sample data conains the NaN values:
data = np.array([10, 20, np.nan, 40, 50], dtype=float)
print(data)

#Step 2: Detect missing values:
missing_mask = np.isnan(data)
print(missing_mask)
print("Missing values:", np.sum(missing_mask))
#Step 3: Handle missing values:
mean_value = np.nanmean(data)
clean_data = np.where(
    np.isnan(data),
    mean_value,
    data
)
print("Mean:", mean_value)
print("Clean data:", clean_data)
#Step 4: Standardize the clean data:
mean = np.mean(clean_data)
std = np.std(clean_data)
standardized = (clean_data - mean) / std
print("Standardized data:", standardized)

[10. 20. nan 40. 50.]
[False False  True False False]
Missing values: 1
Mean: 30.0
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


## D2. Image Batch Understanding

##### 1. Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

A single RGB image with a height and width of 64 × 64 has three color channels: Red, Green, and Blue. Therefore, its NumPy shape is `(64, 64, 3)`, where the three dimensions represent height, width, and color channels.

When multiple RGB images are stored together as a batch, an additional dimension is added at the beginning to represent the number of images. Therefore, a batch of 16 RGB images has the shape `(16, 64, 64, 3)`.

Here, `16` represents the number of images, `64 × 64` represents the height and width of each image, and `3` represents the RGB channels.

##### 2. Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

The following code creates a batch of 16 RGB images with dimensions 64 × 64. Each pixel is represented using three channels: Red, Green, and Blue.

In [15]:
#Step 1: Create a dummy batch:
import numpy as np
rng = np.random.default_rng(42)
images = rng.integers(
    0, 256,
    size=(16, 64, 64, 3),
    dtype=np.uint8
)
print("Batch shape:", images.shape)

#Step 3: Calculate the average image:
average_image = images.mean(axis=0)
print("Average image shape:", average_image.shape)


Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


##### 4. State the shape of your result and explain why.

The resulting average image has the shape `(64, 64, 3)`. This is because `axis=0` represents the 16 images in the batch, so taking the mean along this axis calculates the average pixel value at each corresponding position across all 16 images.

The height, width, and RGB channel dimensions are not reduced, so they remain `(64, 64, 3)`. In other words, the operation converts 16 separate images into one average RGB image while preserving the original image dimensions.

## D3. Debug the Model Code

### Bug 1: Weight vector shape

`X` has shape `(3, 2)`, which means there are 3 samples and 2 features. Therefore, the weight vector must contain 2 values and have shape `(2,)`.

The original `w` has shape `(3,)`. This makes `X @ w` invalid because matrix multiplication would require `(3, 2) @ (2,)`, but the code attempts `(3, 2) @ (3,)`.

### Bug 2: Incorrect MSE calculation

The original expression is:

`np.mean(y_true - y_pred ** 2)`

Because exponentiation has higher precedence than subtraction, Python evaluates this as:

`np.mean(y_true - (y_pred ** 2))`

For Mean Squared Error, the difference must be calculated first and then squared. Therefore, the correct expression is:

`np.mean((y_true - y_pred) ** 2)`

In [ ]:
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])
w = np.array([0.5, 1.0])
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean((y_true - y_pred) ** 2)
print("Predictions:", y_pred)
print("MSE:", mse)


Predictions: [4.5 6.  7.5]
MSE: 244.16666666666666


## Explanation:
The first bug is the incorrect shape of the weight vector. Since `X` has 2 features, `w` must contain 2 weights. The corrected weight vector therefore has shape `(2,)`.

The second bug is the MSE formula. Due to operator precedence, `y_pred ** 2` is calculated before the subtraction in the original code. Adding parentheses ensures that the prediction error is calculated first and then squared.

After correcting both bugs, the model produces one prediction for each of the 3 samples, and the mean of the squared errors gives the final MSE.

## E1. Per-Column Min–Max Normalization

Min-max normalization scales each feature to a range between 0 and 1. Since this question requires per-column normalization, the minimum and maximum values are calculated separately for each feature column using `axis=0`.

The normalization formula is:

`(X - column_min) / (column_max - column_min)`

NumPy broadcasting automatically applies each column's minimum and maximum to the corresponding column. Therefore, the entire operation is vectorized and does not require explicit loops over rows or columns.

In [ ]:
X = np.array([[10, 100],
              [20, 200],
              [30, 300]], dtype=float)
col_min = X.min(axis=0)
col_max = X.max(axis=0)
normalized = (X - col_min) / (col_max - col_min)
print(normalized)


[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


### Explanation:
 The minimum and maximum are calculated separately for each column. Broadcasting applies each column's scaling parameters to its values.

## E2. Three-Level Score Classification:

The exam scores need to be classified into three categories based on their values. Scores below 40 are classified as "Fail", scores from 40 to 70 inclusive are classified as "Average", and scores above 70 are classified as "Excellent".

I use nested `np.where()` to perform all three classifications in a single vectorized expression. The first `np.where()` checks whether a score is below 40. If it is not, the second `np.where()` checks whether the score is less than or equal to 70. This avoids explicit loops and if/else statements.

In [ ]:
scores = np.array([25, 40, 55, 70, 71, 90])
labels = np.where(
    scores < 40,
    "Fail",
    np.where(
        scores <= 70,
        "Average",
        "Excellent"
    )
)
print(labels)

['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


### Explanation:
The outer np.where() identifies scores below 40. For the remaining scores, the inner np.where() separates Average (up to and including 70) from Excellent (above 70).